version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "4321:80"
    volumes:
      - /home/max/Music:/var/www/m
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    restart: always
